#DB Setting

#Driver
#ezflow.driver = oracle.jdbc.driver.OracleDriver
#ezflow.driver = com.tmax.tibero.jdbc.TbDriver
ezflow.driver = com.ibm.db2.jcc.DB2Driver

#DEV

#DEV
#ezflow.url = jdbc:tibero:thin:@11.11.11.44:8629:tibero
#ezflow.pass = HAUVDBggi+MTKdO+mOVMPw==
#ezflow.user = RMSADM

#QA
#ezflow.url = jdbc:oracle:thin:@172.30.158.143:1532:SSOIDMD
#ezflow.pass = 77+oCcedMeS9CXTCo8I280Pyk9UgF6eQ5P4LupmTvcc=
#ezflow.url = jdbc:oracle:thin:@203.225.27.227:1526:devidm
#ezflow.pass = q+0LhB7S3CrzFgZ/rPm6Kw==

#PRD
#ezflow.url = jdbc:oracle:thin:@203.225.29.60:1527:IDM
#ezflow.pass = q+0LhB7S3CrzFgZ/rPm6Kw==

#ezflow.user = IDMADM

#MARIA
#ezflow.driver=org.mariadb.jdbc.Driver
#ezflow.url=jdbc:mariadb://11.11.11.36:3306/rmsadm?characterEncoding=utf8
#ezflow.url=jdbc:mariadb://11.11.11.36:3306/rmsadm?passwordCharacterEncoding=utf8
#ezflow.pass=HAUVDBggi+MTKdO+mOVMPw==
#ezflow.pass=ENC(zOKq0FWCXr4G949CTt709DqZ3itJoJtH)
#ezflow.user=IDMADM

#DB2
ezflow.url=jdbc:db2://11.11.11.64:50002/rmsdb
ezflow.pass=7OwNNgWpYcggYVgLWBj0aQ==
ezflow.user=db2rms
